---
kind: pipeline
name: publish

environment:
  PLATFORMS: ubuntu:20.04 ubuntu:18.04 debian:10 debian:9

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

steps:
  - name: build
    image: docker:19
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - apk add bash
      - sleep 5 # give docker service time to start
      - |
        for PLATFORM in $${PLATFORMS}; do
          ./build.sh $${PLATFORM} $${DRONE_TAG}
        done

  - name: publish
    image: docker:19
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - apk add curl bash
      - |
        for PLATFORM in $${PLATFORMS}; do
          ./publish.sh $${DRONE_REPO_OWNER} $${DRONE_REPO_NAME} $${DRONE_TAG} "htop-$${DRONE_TAG}-$${PLATFORM}"
        done

trigger:
  event:
    - tag
