---
kind: pipeline
name: build

environment:
  PLATFORMS: ubuntu:2004 ubuntu:1804 debian:10 debian:9

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

steps:
  - name: build
    image: docker:19
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - |
        for PLATFORM in $${PLATFORMS}; do
          ./build.sh ${PLATFORM} $${DRONE_TAG}
        done

---
kind: pipeline
name: publish
depends_on:
  - build

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

steps:
  - name: install
    commands: apk add curl

  - name: build
    image: docker:19
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - ./build.sh ubuntu:18.04 $${DRONE_TAG}

  - name: publish
    image: docker:19
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - ./publish.sh $${DRONE_REPO_NAME} $${DRONE_REPO} $${DRONE_TAG} "htop-$${DRONE_TAG}-ubuntu:18.04"

trigger:
  event:
    - tag
